PUID: '1000'
PGID: '1000'
PUSER: shadow-gust
PGROUP: shadow-gust
BASE_DIR: !!python/object/apply:pathlib.PosixPath
- /mnt/Storage/Projects/SIMPLE/ret
VOLUMES_DIR: !!python/object/apply:pathlib.PosixPath
- /mnt/Storage/Projects/SIMPLE/ret/volumes
DOCKER_DIR: !!python/object/apply:pathlib.PosixPath
- /mnt/Storage/Projects/SIMPLE/ret/docker
SCRIPTS_DIR: !!python/object/apply:pathlib.PosixPath
- /mnt/Storage/Projects/SIMPLE/ret/scripts
DOMAIN: ''
EMAIL: ''
SUBDOMAINS: ''
SERVICES: {}
TZ: Asia/Kolkata
HOSTNAME: The-WAR-Machine
UMASK: '0022'
SWAG_STAGING: 'false'
AUTO_GENERATE_PASSWORDS: true
